import { TChallenge } from '../_types/types';

export const prevDummySlide = {
  category: 'lifestyle',
  content: 'dummy',
  createdBy: '2024-01-01',
  endDate: '2024-01-01',
  id: -1,
  imageURL: '',
  isProgress: 'LF',
  challengeParticipants: [{ count: 0 }],
  challengeVerify: [{ count: 0 }],
  participantsCount: 100,
  verificationsCount: 100,
  rating: 5,
  startDate: '2024-01-01',
  tags: null,
  title: 'dummy',
};

export const nextDummySlide = {
  category: 'lifestyle',
  content: 'dummy',
  createdBy: '2024-01-01',
  endDate: '2024-01-01',
  id: -5,
  imageURL: '',
  isProgress: 'LF',
  challengeParticipants: [{ count: 0 }],
  challengeVerify: [{ count: 0 }],
  participantsCount: 100,
  verificationsCount: 100,
  rating: 5,
  startDate: '2024-01-01',
  tags: null,
  title: 'dummy',
};

export const loadingSlides: TChallenge[] = [
  {
    category: 'lifestyle',
    content: '불러오는 중...',
    createdBy: '2024-01-01',
    endDate: '2024-01-01',
    id: -1,
    imageURL: '',
    isProgress: 'LF',
    participants: 100,
    verifications: 100,
    rating: 5,
    startDate: '2024-01-01',
    tags: null,
    title: '불러오는 중...',
  },
  {
    category: 'lifestyle',
    content: '불러오는 중...',
    createdBy: '2024-01-01',
    endDate: '2024-01-01',
    id: -2,
    imageURL: '',
    isProgress: 'LF',
    participants: 100,
    verifications: 100,
    rating: 5,
    startDate: '2024-01-01',
    tags: null,
    title: '불러오는 중...',
  },
  {
    category: 'lifestyle',
    content: '불러오는 중...',
    createdBy: '2024-01-01',
    endDate: '2024-01-01',
    id: -3,
    imageURL: '',
    isProgress: 'LF',
    participants: 100,
    verifications: 100,
    rating: 5,
    startDate: '2024-01-01',
    tags: null,
    title: '불러오는 중...',
  },
  {
    category: 'lifestyle',
    content: '불러오는 중...',
    createdBy: '2024-01-01',
    endDate: '2024-01-01',
    id: -4,
    imageURL: '',
    isProgress: 'LF',
    participants: 100,
    verifications: 100,
    rating: 5,
    startDate: '2024-01-01',
    tags: null,
    title: '불러오는 중...',
  },
  {
    category: 'lifestyle',
    content: '불러오는 중...',
    createdBy: '2024-01-01',
    endDate: '2024-01-01',
    id: -5,
    imageURL: '',
    isProgress: 'LF',
    participants: 100,
    verifications: 100,
    rating: 5,
    startDate: '2024-01-01',
    tags: null,
    title: '불러오는 중...',
  },
];
